import{computed,onUnmounted,ref}from'vue';import{countries}from'../data/countries';import{shuffle}from'../utils';import{saveBest}from'../stores';import{submitScore}from'../services/ranking';import{sound,vibrate}from'../audio';import type{Country,GameStatus,Question}from'../types'
export function useClassicGame(){const status=ref<GameStatus>('idle'),score=ref(0),time=ref(10),question=ref<Question>(),selected=ref(''),countdown=ref(3),isRecord=ref(false);let timer=0,used=new Set<string>()
function makeQuestion(){if(used.size>=countries.length-4)used.clear();const pool=countries.filter(c=>!used.has(c.code)),country=shuffle(pool)[0];used.add(country.code);question.value={country,answers:shuffle([country,...shuffle(countries.filter(c=>c.code!==country.code)).slice(0,3)])};selected.value='';time.value=10}
function runTimer(){clearInterval(timer);timer=window.setInterval(()=>{time.value--;if(time.value>0)sound.countdown(time.value);if(time.value<=0)finish('wrong')},1000)}
function begin(){score.value=0;used.clear();status.value='countdown';countdown.value=3;const c=window.setInterval(()=>{countdown.value--;sound.tick();if(countdown.value===0){clearInterval(c);makeQuestion();status.value='playing';runTimer()}},700)}
function answer(c:Country){if(status.value!=='playing'||!question.value)return;selected.value=c.code;clearInterval(timer);if(c.code===question.value.country.code){status.value='correct';score.value++;sound.correct();vibrate(35);setTimeout(()=>{makeQuestion();status.value='playing';runTimer()},480)}else finish('wrong')}
function finish(reason:'wrong'|'timeout'){clearInterval(timer);status.value='wrong';sound.wrong();vibrate([80,50,120]);isRecord.value=saveBest(score.value);submitScore(score.value);setTimeout(()=>{status.value='gameOver';if(isRecord.value)sound.record()},650)}
function pause(){if(status.value==='playing'){clearInterval(timer);status.value='paused'}else if(status.value==='paused'){status.value='playing';runTimer()}}
onUnmounted(()=>clearInterval(timer));return{status,score,time,question,selected,countdown,isRecord,progress:computed(()=>time.value/10*100),begin,answer,pause}}
