import{computed,onUnmounted,ref}from'vue';import{countries}from'../data/countries';import{shuffle}from'../utils';import{submitScore}from'../services/ranking';import{player,saveTimeAttackBest}from'../stores';import{sound,vibrate}from'../audio';import type{Country,GameStatus,Question}from'../types'
export function useTimeAttack(){const status=ref<GameStatus>('idle'),score=ref(0),time=ref(60),question=ref<Question>(),selected=ref(''),countdown=ref(3),best=ref(player.timeAttackBest);let timer=0,transition=0,used=new Set<string>()
function makeQuestion(){if(used.size>=countries.length-4)used.clear();const available=countries.filter(c=>!used.has(c.code)),country=shuffle(available)[0];used.add(country.code);question.value={country,answers:shuffle([country,...shuffle(countries.filter(c=>c.code!==country.code)).slice(0,3)])};selected.value='';status.value='playing'}
function finish(){clearInterval(timer);clearTimeout(transition);status.value='gameOver';if(saveTimeAttackBest(score.value)){best.value=score.value;sound.record()}else sound.wrong();submitScore(score.value,'timeAttack')}
function runTimer(){clearInterval(timer);timer=window.setInterval(()=>{time.value--;if(time.value>0)sound.countdown(time.value);if(time.value<=0)finish()},1000)}
function begin(){clearInterval(timer);clearTimeout(transition);score.value=0;time.value=60;used.clear();status.value='countdown';countdown.value=3;const pre=window.setInterval(()=>{countdown.value--;sound.tick();if(countdown.value===0){clearInterval(pre);makeQuestion();runTimer()}},700)}
function answer(country:Country){if(status.value!=='playing'||!question.value)return;selected.value=country.code;if(country.code===question.value.country.code){score.value++;status.value='correct';sound.correct();vibrate(30)}else{time.value=Math.max(0,time.value-2);status.value='wrong';sound.wrong();vibrate([50,30,70]);if(time.value===0){finish();return}}transition=window.setTimeout(makeQuestion,360)}
function pause(){if(status.value==='playing'){clearInterval(timer);status.value='paused'}else if(status.value==='paused'){status.value='playing';runTimer()}}
onUnmounted(()=>{clearInterval(timer);clearTimeout(transition)});return{status,score,time,question,selected,countdown,best,progress:computed(()=>time.value/60*100),begin,answer,pause}}
